In [ ]:
import d2l_helper

In [ ]:
x=d2l_helper.arange(12)
print(x.numel())
print(x.shape)
print(x.reshape(3,4))

12
torch.Size([12])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [ ]:
x=d2l_helper.tensor([1,3,4,5])
y=d2l_helper.tensor([2,4,6,4])
x+y,x-y,x/y,x*y

(tensor([ 3,  7, 10,  9]),
 tensor([-1, -1, -2,  1]),
 tensor([0.5000, 0.7500, 0.6667, 1.2500]),
 tensor([ 2, 12, 24, 20]))

In [ ]:
d2l_helper.exp(x)

tensor([  2.7183,  20.0855,  54.5981, 148.4132])

In [ ]:
X=d2l_helper.arange(12,dtype=d2l_helper.float32).reshape(3,4)
Y=d2l_helper.tensor([[1,45,6,3],[1,4,7,8],[2,4,6,7]])
d2l_helper.cat((X,Y),dim=0),d2l_helper.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1., 45.,  6.,  3.],
         [ 1.,  4.,  7.,  8.],
         [ 2.,  4.,  6.,  7.]]),
 tensor([[ 0.,  1.,  2.,  3.,  1., 45.,  6.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  4.,  7.,  8.],
         [ 8.,  9., 10., 11.,  2.,  4.,  6.,  7.]]))

In [11]:
X==Y

tensor([[False, False, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
#注意广播机制需要满足的条件：若两个张量在某维度上大小相等，或者其中一个张量在该维度上大小为 1
a=d2l_helper.arange(3).reshape(1,3)
b=d2l_helper.arange(2).reshape(2,1)
print(a,b)
a+b

tensor([[0, 1, 2]]) tensor([[0],
        [1]])


tensor([[0, 1, 2],
        [1, 2, 3]])

In [15]:
#节省内存
before=id(Y)
Y=Y+X
id(Y)==before

False

In [ ]:
Z=d2l_helper.zeros_like(Y)
print(id(Z))
Z[:]=X+Y
print(id(Z))

1890592172832
1890592172832


In [17]:
before=id(X)
X+=Y
id(X)==before

True

In [ ]:
A=X.numpy()
B=d2l_helper.tensor(A)
type(A)

numpy.ndarray

In [19]:
#本节练习题
X<Y,X>Y

(tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False,  True,  True,  True],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

In [ ]:
#数据预处理

In [ ]:
import os
import d2l_helper

In [25]:
#创建并写入csv文件
os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file=os.path.join('..','data','house_tiny.csv')
with open(data_file,'w')as f:
    f.write('Numrooms,Alley,Price\n')
    f.write('5,train,80000\n')
    f.write('3,pave,90002\n')
    f.write('6,walk,5808\n')
    f.write('NA,pave,8000\n')


In [26]:
#注意这个地方读取csv文件里的内容是data_file而不是csv文件
import pandas as pd
data=pd.read_csv(data_file)
print(data)

   Numrooms  Alley  Price
0       5.0  train  80000
1       3.0   pave  90002
2       6.0   walk   5808
3       NaN   pave   8000


In [38]:
#处理缺失值
inputs,outputs=data.iloc[:,0:1],data.iloc[:,2]
inputs=inputs.fillna(inputs.mean())


In [39]:
inputs=pd.get_dummies(inputs,dummy_na=True)
print(inputs)

   Numrooms
0  5.000000
1  3.000000
2  6.000000
3  4.666667


In [ ]:
#注意什么时候用dtype,什么时候用astype
#astype(),用在pandas和numpy对象上
#dtype,用在to_numpy()或np.array(),torch.tensor这类转换函数上
X=d2l_helper.tensor(inputs.to_numpy(dtype=int))
y=d2l_helper.tensor(outputs.to_numpy(dtype=int))
X,y


(tensor([[5],
         [3],
         [6],
         [4]], dtype=torch.int32),
 tensor([80000, 90002,  5808,  8000], dtype=torch.int32))

In [ ]:
#课后练习题,注意方法是idxmax()而不是idmax(),idxmax()是返回最大值的列所在的标签
data=data.drop(columns=data.isna().sum().idxmax())
data=data.fillna(0)
tensor=d2l_helper.tensor(data.to_numpy(dtype=float))

In [ ]:
#线性代数
#矩阵

tensor([0, 1, 2, 3])

In [ ]:
A=d2l_helper.randn(5,4)
A

tensor([[ 0.7564,  0.9785, -0.5037, -0.0675],
        [-0.6911,  0.4641,  0.0842, -0.5729],
        [-0.1638,  0.3351, -0.0726, -0.7419],
        [-1.2270,  0.2646,  0.9558,  2.5278],
        [-2.0082, -0.5033, -0.9480,  1.9012]])

In [48]:
A.T

tensor([[ 0.7564, -0.6911, -0.1638, -1.2270, -2.0082],
        [ 0.9785,  0.4641,  0.3351,  0.2646, -0.5033],
        [-0.5037,  0.0842, -0.0726,  0.9558, -0.9480],
        [-0.0675, -0.5729, -0.7419,  2.5278,  1.9012]])

In [ ]:
#注意这里的写法，torch.arange(,dtype=torch.float32)
A=d2l_helper.arange(20,dtype=d2l_helper.float32).reshape(4,5)
B=A.clone()
B

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])

In [ ]:
#按照元素进行运算（Hadamard积）
A*B

tensor([[  0.,   1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.,  81.],
        [100., 121., 144., 169., 196.],
        [225., 256., 289., 324., 361.]])

In [55]:
#如何进行矩阵的降维（求和）
A_sum_axis1=A.sum(axis=1)
print(A_sum_axis1)
A_sum_axis0=A.sum(axis=0)
print(A_sum_axis0)

tensor([10., 35., 60., 85.])
tensor([30., 34., 38., 42., 46.])


In [56]:
print(A.sum())
print(A.sum(axis=[0,1]))

tensor(190.)
tensor(190.)


In [57]:
#平均值
print(A.mean())
print(A.sum()/A.numel())

tensor(9.5000)
tensor(9.5000)


In [58]:
print(A.mean(axis=1))
print(A.mean(axis=0))

tensor([ 2.,  7., 12., 17.])
tensor([ 7.5000,  8.5000,  9.5000, 10.5000, 11.5000])


In [60]:
#非降维求和
sum_A=A.sum(axis=1,keepdims=True)
sum_A

tensor([[10.],
        [35.],
        [60.],
        [85.]])

In [ ]:
#求累计总和 .cumsum()
A.cumsum(axis=1)

tensor([[ 0.,  1.,  3.,  6., 10.],
        [ 5., 11., 18., 26., 35.],
        [10., 21., 33., 46., 60.],
        [15., 31., 48., 66., 85.]])

In [ ]:
#点积（dot product)
y=d2l_helper.ones(4,dtype=d2l_helper.float32)
x=d2l_helper.tensor([1,2,3,4],dtype=d2l_helper.float32)
print(x*y)
print(d2l_helper.dot(x,y))

tensor([1., 2., 3., 4.])
tensor(10.)


In [ ]:
#向量积
A=d2l_helper.arange(30,dtype=d2l_helper.float32).reshape(5,6)
B=d2l_helper.randn(24,dtype=d2l_helper.float32).reshape(6,4)
d2l_helper.mm(A,B)

tensor([[  1.7683,  -8.0389,  -8.9692,  -0.7106],
        [-11.9493, -19.8815, -26.7707,   5.5581],
        [-25.6668, -31.7242, -44.5723,  11.8268],
        [-39.3844, -43.5668, -62.3738,  18.0955],
        [-53.1020, -55.4094, -80.1754,  24.3642]])

In [ ]:
#范数
#计算L2范数,注意这个地方的范式计算必须要规定变量的数值类型
u=d2l_helper.tensor([3,-4],dtype=d2l_helper.float32)
d2l_helper.norm(u)

tensor(5.)

In [ ]:
#L1范数
d2l_helper.abs(u).sum()

tensor(7.)

In [ ]:
C=d2l_helper.arange(30,dtype=d2l_helper.float32).reshape(5,6)
d2l_helper.norm(C)


tensor(92.4932)

In [ ]:
#本节练习
A=d2l_helper.arange(25).reshape(5,5)
B=A.T
C=B.T
A==C

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [ ]:
A=d2l_helper.randn(20).reshape(5,4)
B=d2l_helper.randn(20).reshape(5,4)
C=A.T+B.T
D=(A+B).T
C==D

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [ ]:
A=d2l_helper.randn(25).reshape(5,5)
D=A+A.T
D==D.T

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [ ]:
X=d2l_helper.randn(24).reshape(2,3,4)
len(X)

2

In [ ]:
#为了避免广播机制，在A.sum(axis=1)后加入unsqueeze(1),把张量维度从(m,)变为（m,1）
A=d2l_helper.randn(20).reshape(4,5)
print(A/A.sum(axis=1).unsqueeze(1))
#或者是
print(A/A.sum(axis=1,keepdim=True))

tensor([[ 0.0778,  0.1973,  0.0158,  0.3281,  0.3811],
        [ 0.6821,  1.1443,  0.0959, -0.6947, -0.2276],
        [-0.2058, -4.8960,  5.5841, -6.8640,  7.3817],
        [-2.6344, -0.6104,  4.4276,  0.8153, -0.9981]])
tensor([[ 0.0778,  0.1973,  0.0158,  0.3281,  0.3811],
        [ 0.6821,  1.1443,  0.0959, -0.6947, -0.2276],
        [-0.2058, -4.8960,  5.5841, -6.8640,  7.3817],
        [-2.6344, -0.6104,  4.4276,  0.8153, -0.9981]])


In [ ]:
E=d2l_helper.randn(24).reshape(2,3,4)
print(E.sum(axis=0))
print(E.sum(axis=1))
print(E.sum(axis=2))

tensor([[-2.0572,  0.5776,  0.7255,  1.4066],
        [-0.3656, -1.0766,  2.3430,  0.2160],
        [-0.2465, -2.0560,  1.2562,  1.2166]])
tensor([[-0.1233, -3.2862,  1.3084,  0.4762],
        [-2.5460,  0.7313,  3.0164,  2.3629]])
tensor([[-0.0191, -1.8014,  0.1956],
        [ 0.6716,  2.9183, -0.0253]])


In [ ]:
X=d2l_helper.tensor([[6,7,9],[6,7,9],[6,7,9],[9,9,7]])
len(X)

4