In [2]:
import torch
from torch import nn
from torch.nn import functional as F

In [3]:
x=torch.arange(4)
torch.save(x,'x-file')
x2=torch.load('x-file')
x2

tensor([0, 1, 2, 3])

In [4]:
y=torch.zeros(4)
torch.save([x,y],'x-files')
x2,y2=torch.load('x-files')
(x2,y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [5]:
mydict={'x':x,'y':y}
torch.save(mydict,'mydict')
mydict2=torch.load('mydict')
print(mydict2)

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}


In [6]:
#加载和保存模型参数
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden=nn.Linear(20,256)
        self.output=nn.Linear(256,10)
    def forward(self,x):
        return self.output(F.relu(self.hidden(x)))
net=MLP()
X=torch.rand(2,20)
net(X)

tensor([[-0.1405,  0.1914,  0.0233,  0.0266,  0.0184, -0.1754,  0.0089, -0.0049,
         -0.2520,  0.1078],
        [-0.2486,  0.1904,  0.0648,  0.0791,  0.0105, -0.0655,  0.1497, -0.0740,
         -0.2849,  0.0429]], grad_fn=<AddmmBackward0>)

In [10]:
Y=net(X)

In [7]:
#把模型的参数存储在mlp.params的文件
torch.save(net.state_dict(),'mlp.params')

In [ ]:
#实例化原始多层感知机模型的备份，把原有的存下来的参数再传进去
clone=MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()#.eval()：评估模式

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [11]:
Y_clone=clone(X)
Y_clone==Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])